/**
 * GENERATED by scripts/gen-types.mjs from ../schema/*.schema.json — do not edit by hand.
 * Regenerate with `npm run gen:types` after `python -m autotabml.obs.schema`.
 */

export type RunEvent =
  RunStarted | ExperimentStarted | LLMCall | SandboxFinished | ExperimentScored | DecisionMade | Stopped | RunFinished;
export type RunId = string;
export type Seq = number;
export type Ts = string;
export type Type = "run_started";
export type Target = string;
/**
 * This interface was referenced by `AutoTabMLSchemas`'s JSON-Schema
 * via the `definition` "ProblemType".
 */
export type ProblemType = "binary" | "multiclass" | "regression";
/**
 * This interface was referenced by `AutoTabMLSchemas`'s JSON-Schema
 * via the `definition` "Metric".
 */
export type Metric = "roc_auc" | "log_loss" | "accuracy" | "f1_macro" | "rmse" | "mae" | "r2";
export type Description = string;
export type Seed = number;
export type CvFolds = number;
export type CvRepeats = number;
export type SelectFrac = number;
export type TestFrac = number;
export type ExperimentTimeoutS = number;
export type ExperimentMemoryMb = number;
export type NRows = number;
export type NCols = number;
export type Target1 = string;
export type Name = string;
export type Dtype = string;
/**
 * This interface was referenced by `AutoTabMLSchemas`'s JSON-Schema
 * via the `definition` "ColumnKind".
 */
export type ColumnKind = "numeric" | "categorical" | "boolean" | "datetime" | "text" | "id" | "constant";
export type MissingFrac = number;
export type NUnique = number;
export type Examples = unknown[];
export type Stats = {
  [k: string]: number;
} | null;
export type TopValues = {
  [k: string]: number;
} | null;
export type Flags = string[];
export type Columns = ColumnProfile[];
export type Warnings = string[];
export type SampleRows = {
  [k: string]: unknown;
}[];
export type Proposer = string;
export type RunId1 = string;
export type Seq1 = number;
export type Ts1 = string;
export type Type1 = "experiment_started";
export type ExpId = string;
export type ParentId = string | null;
export type Title = string;
export type Rationale = string;
/**
 * This interface was referenced by `AutoTabMLSchemas`'s JSON-Schema
 * via the `definition` "IdeaCategory".
 */
export type IdeaCategory =
  | "baseline"
  | "preprocessing"
  | "feature_engineering"
  | "model_family"
  | "hyperparameters"
  | "ensembling"
  | "simplification"
  | "repair";
export type Radical = boolean;
export type RunId2 = string;
export type Seq2 = number;
export type Ts2 = string;
export type Type2 = "llm_call";
export type ExpId1 = string | null;
export type Purpose = "draft" | "propose" | "implement" | "repair";
export type Model = string;
export type InputTokens = number;
export type OutputTokens = number;
export type CostUsd = number;
export type LatencyS = number;
export type RunId3 = string;
export type Seq3 = number;
export type Ts3 = string;
export type Type3 = "sandbox_finished";
export type ExpId2 = string;
export type Attempt = number;
export type Ok = boolean;
export type DurationS = number;
export type ErrorKind = string | null;
export type ErrorTail = string | null;
export type RunId4 = string;
export type Seq4 = number;
export type Ts4 = string;
export type Type4 = "experiment_scored";
export type ExpId3 = string;
export type Mean = number;
export type Se = number;
export type Folds = number[];
export type SelectScore = number;
export type FitTimeS = number;
export type Loc = number;
export type RunId5 = string;
export type Seq5 = number;
export type Ts5 = string;
export type Type5 = "decision";
export type ExpId4 = string;
/**
 * This interface was referenced by `AutoTabMLSchemas`'s JSON-Schema
 * via the `definition` "Decision".
 */
export type Decision = "keep" | "discard" | "crash";
export type Reason = string;
export type BestExpId = string;
export type BestCvMean = number;
export type RunId6 = string;
export type Seq6 = number;
export type Ts6 = string;
export type Type6 = "stopped";
export type Reason1 = "ceiling" | "max_experiments" | "max_cost" | "max_time" | "user" | "proposer_failure";
export type Summary = string;
export type RunId7 = string;
export type Seq7 = number;
export type Ts7 = string;
export type Type7 = "run_finished";
export type BestExpId1 = string;
export type DevCvMean = number;
export type SelectScore1 = number;
export type TestScore = number;
export type OptimismGap = number;
export type NExperiments = number;
export type TotalCostUsd = number;
export type WallTimeS = number;
export type Version = number;
export type RunId8 = string;
export type CreatedAt = string;
export type Mode = string;
export type Proposer1 = string;
export type Id = string;
export type ParentId1 = string | null;
export type Code = string;
export type Diff = string;
export type Reason2 = string;
export type SelectScore2 = number | null;
export type FitTimeS1 = number | null;
export type Loc1 = number;
export type RepairAttempts = number;
export type ErrorKind1 = string | null;
export type ErrorTail1 = string | null;
export type LlmCalls = LLMUsage[];
export type CostUsd1 = number;
export type DurationS1 = number;
export type StartedAt = string;
export type Experiments = ExperimentRecord[];
export type BestExpId2 = string | null;
export type Stop = {
  [k: string]: unknown;
} | null;
export type BestExpId3 = string;
export type DevCvMean1 = number;
export type SelectScore3 = number;
export type TestScore1 = number;
export type OptimismGap1 = number;
export type TotalCostUsd1 = number;
export type TotalInputTokens = number;
export type TotalOutputTokens = number;
export type WallTimeS1 = number;

export interface AutoTabMLSchemas {
  event: RunEvent;
  record: RunRecord;
}
/**
 * This interface was referenced by `AutoTabMLSchemas`'s JSON-Schema
 * via the `definition` "RunStarted".
 */
export interface RunStarted {
  run_id: RunId;
  seq?: Seq;
  ts?: Ts;
  type?: Type;
  task: TaskSpec;
  profile: DataProfile;
  config: Config;
  proposer: Proposer;
}
/**
 * This interface was referenced by `AutoTabMLSchemas`'s JSON-Schema
 * via the `definition` "TaskSpec".
 */
export interface TaskSpec {
  target: Target;
  problem_type?: ProblemType | null;
  metric?: Metric | null;
  description?: Description;
  seed?: Seed;
  cv_folds?: CvFolds;
  cv_repeats?: CvRepeats;
  select_frac?: SelectFrac;
  test_frac?: TestFrac;
  experiment_timeout_s?: ExperimentTimeoutS;
  experiment_memory_mb?: ExperimentMemoryMb;
}
/**
 * This interface was referenced by `AutoTabMLSchemas`'s JSON-Schema
 * via the `definition` "DataProfile".
 */
export interface DataProfile {
  n_rows: NRows;
  n_cols: NCols;
  target: Target1;
  problem_type: ProblemType;
  metric: Metric;
  columns: Columns;
  target_summary: TargetSummary;
  warnings?: Warnings;
  sample_rows?: SampleRows;
}
/**
 * This interface was referenced by `AutoTabMLSchemas`'s JSON-Schema
 * via the `definition` "ColumnProfile".
 */
export interface ColumnProfile {
  name: Name;
  dtype: Dtype;
  kind: ColumnKind;
  missing_frac: MissingFrac;
  n_unique: NUnique;
  examples?: Examples;
  stats?: Stats;
  top_values?: TopValues;
  flags?: Flags;
}
export interface TargetSummary {
  [k: string]: unknown;
}
export interface Config {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `AutoTabMLSchemas`'s JSON-Schema
 * via the `definition` "ExperimentStarted".
 */
export interface ExperimentStarted {
  run_id: RunId1;
  seq?: Seq1;
  ts?: Ts1;
  type?: Type1;
  exp_id: ExpId;
  parent_id: ParentId;
  idea: Idea;
}
/**
 * This interface was referenced by `AutoTabMLSchemas`'s JSON-Schema
 * via the `definition` "Idea".
 */
export interface Idea {
  title: Title;
  rationale?: Rationale;
  category: IdeaCategory;
  radical?: Radical;
}
/**
 * This interface was referenced by `AutoTabMLSchemas`'s JSON-Schema
 * via the `definition` "LLMCall".
 */
export interface LLMCall {
  run_id: RunId2;
  seq?: Seq2;
  ts?: Ts2;
  type?: Type2;
  exp_id: ExpId1;
  usage: LLMUsage;
}
/**
 * This interface was referenced by `AutoTabMLSchemas`'s JSON-Schema
 * via the `definition` "LLMUsage".
 */
export interface LLMUsage {
  purpose: Purpose;
  model: Model;
  input_tokens?: InputTokens;
  output_tokens?: OutputTokens;
  cost_usd?: CostUsd;
  latency_s?: LatencyS;
}
/**
 * This interface was referenced by `AutoTabMLSchemas`'s JSON-Schema
 * via the `definition` "SandboxFinished".
 */
export interface SandboxFinished {
  run_id: RunId3;
  seq?: Seq3;
  ts?: Ts3;
  type?: Type3;
  exp_id: ExpId2;
  attempt: Attempt;
  ok: Ok;
  duration_s: DurationS;
  error_kind?: ErrorKind;
  error_tail?: ErrorTail;
}
/**
 * This interface was referenced by `AutoTabMLSchemas`'s JSON-Schema
 * via the `definition` "ExperimentScored".
 */
export interface ExperimentScored {
  run_id: RunId4;
  seq?: Seq4;
  ts?: Ts4;
  type?: Type4;
  exp_id: ExpId3;
  cv: CVScore;
  select_score: SelectScore;
  fit_time_s: FitTimeS;
  loc: Loc;
}
/**
 * This interface was referenced by `AutoTabMLSchemas`'s JSON-Schema
 * via the `definition` "CVScore".
 */
export interface CVScore {
  mean: Mean;
  se: Se;
  folds: Folds;
}
/**
 * This interface was referenced by `AutoTabMLSchemas`'s JSON-Schema
 * via the `definition` "DecisionMade".
 */
export interface DecisionMade {
  run_id: RunId5;
  seq?: Seq5;
  ts?: Ts5;
  type?: Type5;
  exp_id: ExpId4;
  decision: Decision;
  reason: Reason;
  best_exp_id: BestExpId;
  best_cv_mean: BestCvMean;
}
/**
 * This interface was referenced by `AutoTabMLSchemas`'s JSON-Schema
 * via the `definition` "Stopped".
 */
export interface Stopped {
  run_id: RunId6;
  seq?: Seq6;
  ts?: Ts6;
  type?: Type6;
  reason: Reason1;
  report: Report;
  summary: Summary;
}
export interface Report {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `AutoTabMLSchemas`'s JSON-Schema
 * via the `definition` "RunFinished".
 */
export interface RunFinished {
  run_id: RunId7;
  seq?: Seq7;
  ts?: Ts7;
  type?: Type7;
  best_exp_id: BestExpId1;
  dev_cv_mean: DevCvMean;
  select_score: SelectScore1;
  test_score: TestScore;
  optimism_gap: OptimismGap;
  n_experiments: NExperiments;
  total_cost_usd: TotalCostUsd;
  wall_time_s: WallTimeS;
}
/**
 * This interface was referenced by `AutoTabMLSchemas`'s JSON-Schema
 * via the `definition` "RunRecord".
 */
export interface RunRecord {
  version?: Version;
  run_id: RunId8;
  created_at: CreatedAt;
  mode: Mode;
  proposer: Proposer1;
  task: TaskSpec;
  profile: DataProfile;
  config?: Config1;
  experiments?: Experiments;
  best_exp_id?: BestExpId2;
  stop?: Stop;
  final?: FinalScores | null;
  total_cost_usd?: TotalCostUsd1;
  total_input_tokens?: TotalInputTokens;
  total_output_tokens?: TotalOutputTokens;
  wall_time_s?: WallTimeS1;
}
export interface Config1 {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `AutoTabMLSchemas`'s JSON-Schema
 * via the `definition` "ExperimentRecord".
 */
export interface ExperimentRecord {
  id: Id;
  parent_id: ParentId1;
  idea: Idea;
  code: Code;
  diff?: Diff;
  status: Decision;
  reason?: Reason2;
  cv?: CVScore | null;
  select_score?: SelectScore2;
  fit_time_s?: FitTimeS1;
  loc?: Loc1;
  repair_attempts?: RepairAttempts;
  error_kind?: ErrorKind1;
  error_tail?: ErrorTail1;
  llm_calls?: LlmCalls;
  cost_usd?: CostUsd1;
  duration_s?: DurationS1;
  started_at?: StartedAt;
}
/**
 * This interface was referenced by `AutoTabMLSchemas`'s JSON-Schema
 * via the `definition` "FinalScores".
 */
export interface FinalScores {
  best_exp_id: BestExpId3;
  dev_cv_mean: DevCvMean1;
  select_score: SelectScore3;
  test_score: TestScore1;
  optimism_gap: OptimismGap1;
}
