/**
 * GENERATED by scripts/gen-types.mjs from ../schema/*.schema.json — do not edit by hand.
 * Regenerate with `npm run gen:types` after `python -m autotinker.obs.schema`.
 */

export type RunEvent =
  | RunStarted
  | ExperimentStarted
  | LLMCall
  | SandboxFinished
  | ExperimentScored
  | DecisionMade
  | Stopped
  | RunFinished
  | AgentStepStarted
  | AgentReasoning
  | AgentStepFinished
  | SandboxLog
  | HpoTrialEvent
  | ReportReady;
export type RunId = string;
export type Seq = number;
export type Ts = string;
export type Type = "run_started";
export type Target = string;
/**
 * This interface was referenced by `AutoTinkerSchemas`'s JSON-Schema
 * via the `definition` "ProblemType".
 */
export type ProblemType = "binary" | "multiclass" | "regression";
/**
 * This interface was referenced by `AutoTinkerSchemas`'s JSON-Schema
 * via the `definition` "Metric".
 */
export type Metric = "roc_auc" | "log_loss" | "accuracy" | "f1_macro" | "rmse" | "mae" | "r2";
export type Description = string;
export type Seed = number;
export type CvFolds = number;
export type CvRepeats = number;
export type SelectFrac = number;
export type TestFrac = number;
export type ExperimentTimeoutS = number;
export type ExperimentMemoryMb = number;
export type NRows = number;
export type NCols = number;
export type Target1 = string;
export type Name = string;
export type Dtype = string;
/**
 * This interface was referenced by `AutoTinkerSchemas`'s JSON-Schema
 * via the `definition` "ColumnKind".
 */
export type ColumnKind = "numeric" | "categorical" | "boolean" | "datetime" | "text" | "id" | "constant";
export type MissingFrac = number;
export type NUnique = number;
export type Examples = unknown[];
export type Stats = {
  [k: string]: number;
} | null;
export type TopValues = {
  [k: string]: number;
} | null;
export type Flags = string[];
export type Columns = ColumnProfile[];
export type Warnings = string[];
export type SampleRows = {
  [k: string]: unknown;
}[];
export type Proposer = string;
export type RunId1 = string;
export type Seq1 = number;
export type Ts1 = string;
export type Type1 = "experiment_started";
export type ExpId = string;
export type ParentId = string | null;
export type Title = string;
export type Rationale = string;
/**
 * This interface was referenced by `AutoTinkerSchemas`'s JSON-Schema
 * via the `definition` "IdeaCategory".
 */
export type IdeaCategory =
  | "baseline"
  | "preprocessing"
  | "feature_engineering"
  | "model_family"
  | "hyperparameters"
  | "ensembling"
  | "simplification"
  | "repair";
export type Radical = boolean;
export type RunId2 = string;
export type Seq2 = number;
export type Ts2 = string;
export type Type2 = "llm_call";
export type ExpId1 = string | null;
export type Purpose =
  | "draft"
  | "propose"
  | "implement"
  | "repair"
  | "intake"
  | "profiler"
  | "planner"
  | "coder"
  | "debugger"
  | "critic"
  | "judge"
  | "tuner"
  | "ensembler"
  | "reporter";
export type Model = string;
export type InputTokens = number;
export type OutputTokens = number;
export type CostUsd = number;
export type LatencyS = number;
export type RunId3 = string;
export type Seq3 = number;
export type Ts3 = string;
export type Type3 = "sandbox_finished";
export type ExpId2 = string;
export type Attempt = number;
export type Ok = boolean;
export type DurationS = number;
export type ErrorKind = string | null;
export type ErrorTail = string | null;
export type RunId4 = string;
export type Seq4 = number;
export type Ts4 = string;
export type Type4 = "experiment_scored";
export type ExpId3 = string;
export type Mean = number;
export type Se = number;
export type Folds = number[];
export type SelectScore = number;
export type FitTimeS = number;
export type Loc = number;
export type RunId5 = string;
export type Seq5 = number;
export type Ts5 = string;
export type Type5 = "decision";
export type ExpId4 = string;
/**
 * This interface was referenced by `AutoTinkerSchemas`'s JSON-Schema
 * via the `definition` "Decision".
 */
export type Decision = "keep" | "discard" | "crash";
export type Reason = string;
export type BestExpId = string;
export type BestCvMean = number;
export type RunId6 = string;
export type Seq6 = number;
export type Ts6 = string;
export type Type6 = "stopped";
export type Reason1 =
  "ceiling" | "max_experiments" | "max_cost" | "max_time" | "user" | "proposer_failure" | "max_tokens";
export type Summary = string;
export type RunId7 = string;
export type Seq7 = number;
export type Ts7 = string;
export type Type7 = "run_finished";
export type BestExpId1 = string;
export type DevCvMean = number;
export type SelectScore1 = number;
export type TestScore = number;
export type OptimismGap = number;
export type NExperiments = number;
export type TotalCostUsd = number;
export type WallTimeS = number;
export type RunId8 = string;
export type Seq8 = number;
export type Ts8 = string;
export type Type8 = "agent_step_started";
export type ExpId5 = string | null;
export type StepId = string;
export type Role = string;
export type Attempt1 = number;
export type InputSummary = string;
export type RunId9 = string;
export type Seq9 = number;
export type Ts9 = string;
export type Type9 = "agent_reasoning";
export type ExpId6 = string | null;
export type StepId1 = string;
export type Role1 = string;
export type Text = string;
export type RunId10 = string;
export type Seq10 = number;
export type Ts10 = string;
export type Type10 = "agent_step_finished";
export type ExpId7 = string | null;
export type StepId2 = string;
export type Role2 = string;
export type Model1 = string | null;
export type Provider = string | null;
export type Attempt2 = number;
export type Status = "ok" | "error";
export type Plain = string;
export type InputSummary1 = string;
export type Reasoning = string | null;
export type Output = {
  [k: string]: unknown;
} | null;
export type Code = string | null;
export type Diff = string | null;
export type ToolCalls = {
  [k: string]: unknown;
}[];
export type StdoutTail = string | null;
export type StderrTail = string | null;
export type Error = string | null;
export type TokensIn = number;
export type TokensOut = number;
export type TokensCached = number;
export type CostUsd1 = number;
export type WouldBeCostUsd = number;
export type DurationS1 = number;
export type StartedAt = string;
export type RunId11 = string;
export type Seq11 = number;
export type Ts11 = string;
export type Type11 = "sandbox_log";
export type ExpId8 = string;
export type Attempt3 = number;
export type Stream = "stdout" | "stderr";
export type Lines = string[];
export type RunId12 = string;
export type Seq12 = number;
export type Ts12 = string;
export type Type12 = "hpo_trial";
export type ExpId9 = string;
export type Number = number;
export type Value = number | null;
export type State = "complete" | "fail" | "pruned";
export type DurationS2 = number;
export type RunId13 = string;
export type Seq13 = number;
export type Ts13 = string;
export type Type13 = "report_ready";
export type Version = number;
export type RunId14 = string;
export type CreatedAt = string;
export type Mode = string;
export type Proposer1 = string;
export type Id = string;
export type ParentId1 = string | null;
export type Code1 = string;
export type Diff1 = string;
export type Reason2 = string;
export type SelectScore2 = number | null;
export type FitTimeS1 = number | null;
export type Loc1 = number;
export type RepairAttempts = number;
export type ErrorKind1 = string | null;
export type ErrorTail1 = string | null;
export type LlmCalls = LLMUsage[];
export type CostUsd2 = number;
export type DurationS3 = number;
export type StartedAt1 = string;
export type Phase = string | null;
export type Steps = AgentStep[];
export type Trials = HpoTrial[];
export type Experiments = ExperimentRecord[];
export type BestExpId2 = string | null;
export type Stop = {
  [k: string]: unknown;
} | null;
export type BestExpId3 = string;
export type DevCvMean1 = number;
export type SelectScore3 = number;
export type TestScore1 = number;
export type OptimismGap1 = number;
export type TotalCostUsd1 = number;
export type TotalInputTokens = number;
export type TotalOutputTokens = number;
export type WallTimeS1 = number;
export type Steps1 = AgentStep[];
export type Report2 = {
  [k: string]: unknown;
} | null;

export interface AutoTinkerSchemas {
  event: RunEvent;
  record: RunRecord;
}
/**
 * This interface was referenced by `AutoTinkerSchemas`'s JSON-Schema
 * via the `definition` "RunStarted".
 */
export interface RunStarted {
  run_id: RunId;
  seq?: Seq;
  ts?: Ts;
  type?: Type;
  task: TaskSpec;
  profile: DataProfile;
  config: Config;
  proposer: Proposer;
}
/**
 * This interface was referenced by `AutoTinkerSchemas`'s JSON-Schema
 * via the `definition` "TaskSpec".
 */
export interface TaskSpec {
  target: Target;
  problem_type?: ProblemType | null;
  metric?: Metric | null;
  description?: Description;
  seed?: Seed;
  cv_folds?: CvFolds;
  cv_repeats?: CvRepeats;
  select_frac?: SelectFrac;
  test_frac?: TestFrac;
  experiment_timeout_s?: ExperimentTimeoutS;
  experiment_memory_mb?: ExperimentMemoryMb;
}
/**
 * This interface was referenced by `AutoTinkerSchemas`'s JSON-Schema
 * via the `definition` "DataProfile".
 */
export interface DataProfile {
  n_rows: NRows;
  n_cols: NCols;
  target: Target1;
  problem_type: ProblemType;
  metric: Metric;
  columns: Columns;
  target_summary: TargetSummary;
  warnings?: Warnings;
  sample_rows?: SampleRows;
}
/**
 * This interface was referenced by `AutoTinkerSchemas`'s JSON-Schema
 * via the `definition` "ColumnProfile".
 */
export interface ColumnProfile {
  name: Name;
  dtype: Dtype;
  kind: ColumnKind;
  missing_frac: MissingFrac;
  n_unique: NUnique;
  examples?: Examples;
  stats?: Stats;
  top_values?: TopValues;
  flags?: Flags;
}
export interface TargetSummary {
  [k: string]: unknown;
}
export interface Config {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `AutoTinkerSchemas`'s JSON-Schema
 * via the `definition` "ExperimentStarted".
 */
export interface ExperimentStarted {
  run_id: RunId1;
  seq?: Seq1;
  ts?: Ts1;
  type?: Type1;
  exp_id: ExpId;
  parent_id: ParentId;
  idea: Idea;
}
/**
 * This interface was referenced by `AutoTinkerSchemas`'s JSON-Schema
 * via the `definition` "Idea".
 */
export interface Idea {
  title: Title;
  rationale?: Rationale;
  category: IdeaCategory;
  radical?: Radical;
}
/**
 * This interface was referenced by `AutoTinkerSchemas`'s JSON-Schema
 * via the `definition` "LLMCall".
 */
export interface LLMCall {
  run_id: RunId2;
  seq?: Seq2;
  ts?: Ts2;
  type?: Type2;
  exp_id: ExpId1;
  usage: LLMUsage;
}
/**
 * This interface was referenced by `AutoTinkerSchemas`'s JSON-Schema
 * via the `definition` "LLMUsage".
 */
export interface LLMUsage {
  purpose: Purpose;
  model: Model;
  input_tokens?: InputTokens;
  output_tokens?: OutputTokens;
  cost_usd?: CostUsd;
  latency_s?: LatencyS;
}
/**
 * This interface was referenced by `AutoTinkerSchemas`'s JSON-Schema
 * via the `definition` "SandboxFinished".
 */
export interface SandboxFinished {
  run_id: RunId3;
  seq?: Seq3;
  ts?: Ts3;
  type?: Type3;
  exp_id: ExpId2;
  attempt: Attempt;
  ok: Ok;
  duration_s: DurationS;
  error_kind?: ErrorKind;
  error_tail?: ErrorTail;
}
/**
 * This interface was referenced by `AutoTinkerSchemas`'s JSON-Schema
 * via the `definition` "ExperimentScored".
 */
export interface ExperimentScored {
  run_id: RunId4;
  seq?: Seq4;
  ts?: Ts4;
  type?: Type4;
  exp_id: ExpId3;
  cv: CVScore;
  select_score: SelectScore;
  fit_time_s: FitTimeS;
  loc: Loc;
}
/**
 * This interface was referenced by `AutoTinkerSchemas`'s JSON-Schema
 * via the `definition` "CVScore".
 */
export interface CVScore {
  mean: Mean;
  se: Se;
  folds: Folds;
}
/**
 * This interface was referenced by `AutoTinkerSchemas`'s JSON-Schema
 * via the `definition` "DecisionMade".
 */
export interface DecisionMade {
  run_id: RunId5;
  seq?: Seq5;
  ts?: Ts5;
  type?: Type5;
  exp_id: ExpId4;
  decision: Decision;
  reason: Reason;
  best_exp_id: BestExpId;
  best_cv_mean: BestCvMean;
}
/**
 * This interface was referenced by `AutoTinkerSchemas`'s JSON-Schema
 * via the `definition` "Stopped".
 */
export interface Stopped {
  run_id: RunId6;
  seq?: Seq6;
  ts?: Ts6;
  type?: Type6;
  reason: Reason1;
  report: Report;
  summary: Summary;
}
export interface Report {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `AutoTinkerSchemas`'s JSON-Schema
 * via the `definition` "RunFinished".
 */
export interface RunFinished {
  run_id: RunId7;
  seq?: Seq7;
  ts?: Ts7;
  type?: Type7;
  best_exp_id: BestExpId1;
  dev_cv_mean: DevCvMean;
  select_score: SelectScore1;
  test_score: TestScore;
  optimism_gap: OptimismGap;
  n_experiments: NExperiments;
  total_cost_usd: TotalCostUsd;
  wall_time_s: WallTimeS;
}
/**
 * This interface was referenced by `AutoTinkerSchemas`'s JSON-Schema
 * via the `definition` "AgentStepStarted".
 */
export interface AgentStepStarted {
  run_id: RunId8;
  seq?: Seq8;
  ts?: Ts8;
  type?: Type8;
  exp_id: ExpId5;
  step_id: StepId;
  role: Role;
  attempt?: Attempt1;
  input_summary?: InputSummary;
}
/**
 * This interface was referenced by `AutoTinkerSchemas`'s JSON-Schema
 * via the `definition` "AgentReasoning".
 */
export interface AgentReasoning {
  run_id: RunId9;
  seq?: Seq9;
  ts?: Ts9;
  type?: Type9;
  exp_id: ExpId6;
  step_id: StepId1;
  role: Role1;
  text: Text;
}
/**
 * This interface was referenced by `AutoTinkerSchemas`'s JSON-Schema
 * via the `definition` "AgentStepFinished".
 */
export interface AgentStepFinished {
  run_id: RunId10;
  seq?: Seq10;
  ts?: Ts10;
  type?: Type10;
  exp_id: ExpId7;
  step: AgentStep;
}
/**
 * One step of one agent (or of a deterministic actor such as the executor) inside an experiment.
 *
 * LLM steps carry the model/provider and token accounting; executor/ablation/tune steps carry the sandbox
 * tails. `plain` is the one-line, plain-language message shown in the chat.
 *
 * This interface was referenced by `AutoTinkerSchemas`'s JSON-Schema
 * via the `definition` "AgentStep".
 */
export interface AgentStep {
  step_id?: StepId2;
  role: Role2;
  model?: Model1;
  provider?: Provider;
  attempt?: Attempt2;
  status?: Status;
  plain?: Plain;
  input_summary?: InputSummary1;
  reasoning?: Reasoning;
  output?: Output;
  code?: Code;
  diff?: Diff;
  tool_calls?: ToolCalls;
  stdout_tail?: StdoutTail;
  stderr_tail?: StderrTail;
  error?: Error;
  tokens_in?: TokensIn;
  tokens_out?: TokensOut;
  tokens_cached?: TokensCached;
  cost_usd?: CostUsd1;
  would_be_cost_usd?: WouldBeCostUsd;
  duration_s?: DurationS1;
  started_at?: StartedAt;
}
/**
 * This interface was referenced by `AutoTinkerSchemas`'s JSON-Schema
 * via the `definition` "SandboxLog".
 */
export interface SandboxLog {
  run_id: RunId11;
  seq?: Seq11;
  ts?: Ts11;
  type?: Type11;
  exp_id: ExpId8;
  attempt?: Attempt3;
  stream?: Stream;
  lines: Lines;
}
/**
 * This interface was referenced by `AutoTinkerSchemas`'s JSON-Schema
 * via the `definition` "HpoTrialEvent".
 */
export interface HpoTrialEvent {
  run_id: RunId12;
  seq?: Seq12;
  ts?: Ts12;
  type?: Type12;
  exp_id: ExpId9;
  trial: HpoTrial;
}
/**
 * This interface was referenced by `AutoTinkerSchemas`'s JSON-Schema
 * via the `definition` "HpoTrial".
 */
export interface HpoTrial {
  number: Number;
  params?: Params;
  value?: Value;
  state?: State;
  duration_s?: DurationS2;
}
export interface Params {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `AutoTinkerSchemas`'s JSON-Schema
 * via the `definition` "ReportReady".
 */
export interface ReportReady {
  run_id: RunId13;
  seq?: Seq13;
  ts?: Ts13;
  type?: Type13;
  report: Report1;
}
export interface Report1 {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `AutoTinkerSchemas`'s JSON-Schema
 * via the `definition` "RunRecord".
 */
export interface RunRecord {
  version?: Version;
  run_id: RunId14;
  created_at: CreatedAt;
  mode: Mode;
  proposer: Proposer1;
  task: TaskSpec;
  profile: DataProfile;
  config?: Config1;
  experiments?: Experiments;
  best_exp_id?: BestExpId2;
  stop?: Stop;
  final?: FinalScores | null;
  total_cost_usd?: TotalCostUsd1;
  total_input_tokens?: TotalInputTokens;
  total_output_tokens?: TotalOutputTokens;
  wall_time_s?: WallTimeS1;
  steps?: Steps1;
  report?: Report2;
  usage?: Usage;
}
export interface Config1 {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `AutoTinkerSchemas`'s JSON-Schema
 * via the `definition` "ExperimentRecord".
 */
export interface ExperimentRecord {
  id: Id;
  parent_id: ParentId1;
  idea: Idea;
  code: Code1;
  diff?: Diff1;
  status: Decision;
  reason?: Reason2;
  cv?: CVScore | null;
  select_score?: SelectScore2;
  fit_time_s?: FitTimeS1;
  loc?: Loc1;
  repair_attempts?: RepairAttempts;
  error_kind?: ErrorKind1;
  error_tail?: ErrorTail1;
  llm_calls?: LlmCalls;
  cost_usd?: CostUsd2;
  duration_s?: DurationS3;
  started_at?: StartedAt1;
  phase?: Phase;
  steps?: Steps;
  trials?: Trials;
}
/**
 * This interface was referenced by `AutoTinkerSchemas`'s JSON-Schema
 * via the `definition` "FinalScores".
 */
export interface FinalScores {
  best_exp_id: BestExpId3;
  dev_cv_mean: DevCvMean1;
  select_score: SelectScore3;
  test_score: TestScore1;
  optimism_gap: OptimismGap1;
}
export interface Usage {
  [k: string]: unknown;
}
