// Generate src/lib/schema.ts from the Python-generated JSON Schemas in ../schema.
// Both schemas share $defs (CVScore, Idea, ...), so we merge them into one wrapper
// schema and compile once — compiling separately would emit duplicate interfaces.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { compile } from "json-schema-to-typescript";

const here = dirname(fileURLToPath(import.meta.url));
const schemaDir = resolve(here, "../../schema");
const events = JSON.parse(readFileSync(resolve(schemaDir, "events.schema.json"), "utf8"));
const record = JSON.parse(readFileSync(resolve(schemaDir, "run_record.schema.json"), "utf8"));

const { $defs: recordDefs, ...recordRoot } = record;
const $defs = { ...events.$defs, ...recordDefs, RunRecord: recordRoot };
for (const [name, def] of Object.entries(events.$defs)) {
  if (recordDefs[name] && JSON.stringify(recordDefs[name]) !== JSON.stringify(def)) {
    throw new Error(`$defs.${name} differs between events and run_record schemas`);
  }
}

const wrapper = {
  title: "AutoTabMLSchemas",
  type: "object",
  additionalProperties: false,
  properties: {
    event: { title: "RunEvent", oneOf: events.oneOf },
    record: { $ref: "#/$defs/RunRecord" },
  },
  required: ["event", "record"],
  $defs,
};

const ts = await compile(wrapper, "AutoTabMLSchemas", {
  additionalProperties: false,
  bannerComment:
    "/**\n * GENERATED by scripts/gen-types.mjs from ../schema/*.schema.json — do not edit by hand.\n * Regenerate with `npm run gen:types` after `python -m autotabml.obs.schema`.\n */",
  unreachableDefinitions: true,
  strictIndexSignatures: false,
});
writeFileSync(resolve(here, "../src/lib/schema.ts"), ts);
console.log("wrote src/lib/schema.ts");
