import type { ExpStatus } from "@/lib/run-state";
import { CATEGORY_LABEL } from "@/lib/format";

const STATUS_STYLE: Record<ExpStatus, string> = {
  keep: "text-keep border-keep/40 bg-keep/10",
  discard: "text-ink-3 border-rule-strong bg-transparent",
  crash: "text-crash border-crash/40 bg-crash/10",
  running: "text-best border-best/40 bg-best-soft",
};

export function StatusBadge({ status }: { status: ExpStatus }) {
  return (
    <span className={`inline-flex items-center gap-1 rounded-full border px-2 py-px text-[11px] font-medium uppercase tracking-[0.06em] ${STATUS_STYLE[status]}`}>
      {status === "running" && <span className="size-1.5 animate-pulse rounded-full bg-best" aria-hidden />}
      {status}
    </span>
  );
}

export function CategoryChip({ category }: { category: string }) {
  return <span className="text-[11px] tracking-wide text-ink-3">{CATEGORY_LABEL[category] ?? category}</span>;
}

export function RadicalBadge() {
  return (
    <span
      title="A different model family or approach. The stop rule counts these: a run cannot call a ceiling until several radical attempts have failed."
      className="rounded-sm bg-ink px-1.5 py-px text-[10px] font-semibold uppercase tracking-[0.08em] text-paper"
    >
      radical
    </span>
  );
}

export function ProposerBadge({ proposer }: { proposer: string | null }) {
  if (!proposer) return null;
  if (proposer === "heuristic")
    return (
      <span className="inline-flex items-center gap-2 rounded-full border border-rule-strong bg-paper-2 px-3 py-1 text-xs text-ink-2">
        <svg viewBox="0 0 12 12" className="size-3" aria-hidden>
          <rect x="1" y="1" width="10" height="10" rx="2" fill="none" stroke="currentColor" strokeWidth="1.3" />
          <path d="M3.5 6h5M6 3.5v5" stroke="currentColor" strokeWidth="1.3" />
        </svg>
        Generated by the offline heuristic proposer (no LLM)
      </span>
    );
  return (
    <span className="inline-flex items-center gap-2 rounded-full border border-rule-strong bg-paper-2 px-3 py-1 text-xs text-ink-2">
      Proposer: <span className="font-mono text-[11px] text-ink">{proposer}</span>
    </span>
  );
}
